language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false
git:
  depth: 99999999

after_success:
  - julia -e 'cd(Pkg.dir("GBIF")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("GBIF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("GBIF")); include(joinpath("docs", "make.jl"))'
