language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

allow_failures:
  - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("GBIF")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("GBIF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
