site_name:        GBIF.jl
repo_url:         https://github.com/EcoJulia/GBIF.jl
site_description: Access to GBIF data
site_author:      Timothée Poisot
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'amber'
  font:
    text: 'Overpass'
    code: 'Overpass Mono'

repo_name: 'EcoJulia/GBIF.jl'
repo_url: 'https://github.com/EcoJulia/GBIF.jl'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: build

markdown_extensions:
  - admonition
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite:
      guess_lang: false

pages:
  - Home: index.md
  - Getting data: occurrences.md
  - Filtering records: qaqc.md
