name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  release:

concurrency:
    group: doc-build-pipeline
    cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  BuildManual:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            folder: [manual/dataviz, manual/distributions, manual/generation, manual/layers, manual/polygons, manual/retrieval, manual/sdm, manual/usage, manual/usecases]
    steps:
      - uses: actions/checkout@v4
      - name: Prepare the artifact name
        id: prep_artifact_name
        run: |
            if [ "${{ matrix.folder }}" != "" ] ; then
                name="${{ matrix.folder }}"
            fi
            name=$(echo -n "$name" | sed -e 's/[ \t:\/\\"<>|*?]/-/g' -e 's/--*/-/g')
            echo "ARTIFACT_NAME=$name" >> $GITHUB_ENV
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: "Bootstrap the package"
        run: julia --project=. bootstrap.jl
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DATADEPS_ALWAYS_ACCEPT: true
        run: julia --project=docs/ --threads=auto docs/build.jl ${{ matrix.folder }}
      - name: "Upload the folder ${{ matrix.folder }}"
        uses: actions/upload-artifact@v4
        with:
          path: |
            docs/src/manual
          name: build-${{ env.ARTIFACT_NAME }}
  BuildDocumentation:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 1
        matrix:
            pkg: [OccurrencesInterface, GBIF, PseudoAbsences, SDeMo, Fauxcurrences, SimpleSDMLayers, SimpleSDMDatasets, SimpleSDMPolygons, Phylopic]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: "Bootstrap the package"
        run: julia --project=./${{ matrix.pkg }} ${{ matrix.pkg }}/bootstrap.jl
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        working-directory: ${{ matrix.pkg }}/
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=${{ matrix.pkg }}/docs/ ${{ matrix.pkg }}/docs/make.jl
  SpeciesDistributionToolkit:
    needs: [BuildManual, BuildDocumentation]
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Merge the manual artifacts"
        uses: actions/upload-artifact/merge@v4
        with:
            name: manual-compiled
            delete-merged: true
      - name: "Put the compiled manual in its place"
        uses: actions/download-artifact@v8
        with:
            name: manual-compiled
            path: docs/src
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: "Bootstrap the package"
        run: julia --project=. bootstrap.jl
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DATADEPS_ALWAYS_ACCEPT: true
        run: julia --project=docs/ --threads=auto docs/make.jl
