name: Documentation (Datasets)
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:

jobs:
  Documenter:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - uses: julia-actions/cache@v1
      - name: Setup the component packages (globally)
        run: julia --project bootstrap.jl
      - name: "Instantiate SimpleSDMDatasets documentation"
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        working-directory: SimpleSDMDatasets/
      - name: "Build SimpleSDMDatasets documentation"
        run: julia --project=SimpleSDMDatasets/docs/ SimpleSDMDatasets/docs/make.jl
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}