name: Documentation (SDT)
on:
  push:
    branches: [main]
    tags: '*'
  pull_request:

jobs:
  Documenter:
    permissions:
      contents: write
      pull-requests: read
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - uses: julia-actions/cache@v1
      - name: Setup the component packages (globally)
        run: julia --project bootstrap.jl
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}